"""Deploy an ADK agent to Vertex AI Agent Engine using source-file deployment.

This script demonstrates the full deployment lifecycle:
    - Package source code and dependencies
    - Pass environment variables from .env to the deployed agent
    - Create, update, delete, and test deployments
    - Track deployment state in a local JSON file

Usage:
    uv run python deploy/deploy.py                   # deploy
    uv run python deploy/deploy.py --update           # update existing
    uv run python deploy/deploy.py --delete           # delete
    uv run python deploy/deploy.py --info             # show deployment info
    uv run python deploy/deploy.py --test             # test deployed agent
    uv run python deploy/deploy.py --skip-local-test  # skip pre-deploy smoke test

What Agent Engine provides automatically (no config needed):
    - Persistent session management (cloud-based)
    - Cloud Monitoring (metrics dashboard)
    - Cloud Logging (runtime event logs)

What this script enables via env vars:
    - Cloud Trace: GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY=true
    - Prompt/response logging: OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT=true
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import sys
import tomllib
import warnings
from datetime import datetime
from pathlib import Path

import dotenv

# ---------------------------------------------------------------------------
# Paths — all relative to the project root (one level up from deploy/)
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEPLOY_DIR = Path(__file__).resolve().parent

# Load .env so we can read GOOGLE_CLOUD_PROJECT and other settings
dotenv.load_dotenv(dotenv_path=PROJECT_ROOT / ".env")

# Add project root to sys.path so agent packages can be imported
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Suppress experimental-feature warnings from the Vertex AI SDK
warnings.filterwarnings("ignore", message=".*EXPERIMENTAL.*")

# ---------------------------------------------------------------------------
# Deployment configuration
# ---------------------------------------------------------------------------

# The entrypoint module contains the AdkApp wrapper. Agent Engine imports
# this module and uses the `app` object as the entry point.
ENTRYPOINT_MODULE = "deploy.entrypoint"
ENTRYPOINT_OBJECT = "app"

DISPLAY_NAME = "vertex-agent-engine-tutorial"
DESCRIPTION = "Tutorial multi-agent system deployed to Vertex AI Agent Engine."
TEST_MESSAGE = "Hello! What can you do?"

# Path to the JSON file that tracks deployment state
DEPLOYMENT_FILE = DEPLOY_DIR / "app" / "deployment.json"

# ---------------------------------------------------------------------------
# ADK class methods spec
# ---------------------------------------------------------------------------
# Source-file deployment requires an explicit list of the API methods that
# Agent Engine should expose. These are the standard AdkApp methods —
# the same for every ADK agent deployment.
#
# This list was generated by introspecting AdkApp via:
#   from vertexai._genai._agent_engines_utils import (
#       _get_registered_operations,
#       _generate_class_methods_spec_or_raise,
#   )
#   ops = _get_registered_operations(app)
#   spec = _generate_class_methods_spec_or_raise(ops)

ADK_CLASS_METHODS = [
    {
        "name": "async_stream_query",
        "api_mode": "async_stream",
        "parameters": {
            "type": "object",
            "required": ["message", "user_id"],
            "properties": {
                "message": {"anyOf": [{"type": "string"}, {"type": "object", "additionalProperties": True}]},
                "user_id": {"type": "string"},
                "session_id": {"type": "string", "nullable": True},
                "session_events": {"type": "array", "nullable": True},
                "run_config": {"type": "object", "nullable": True},
            },
        },
    },
    {
        "name": "stream_query",
        "api_mode": "stream",
        "parameters": {
            "type": "object",
            "required": ["message", "user_id"],
            "properties": {
                "message": {"anyOf": [{"type": "string"}, {"type": "object", "additionalProperties": True}]},
                "user_id": {"type": "string"},
                "session_id": {"type": "string", "nullable": True},
                "run_config": {"type": "object", "nullable": True},
            },
        },
    },
    {
        "name": "streaming_agent_run_with_events",
        "api_mode": "async_stream",
        "parameters": {
            "type": "object",
            "required": ["request_json"],
            "properties": {"request_json": {"type": "string"}},
        },
    },
    {
        "name": "create_session",
        "api_mode": "",
        "parameters": {
            "type": "object",
            "required": ["user_id"],
            "properties": {
                "user_id": {"type": "string"},
                "session_id": {"type": "string", "nullable": True},
                "state": {"type": "object", "nullable": True},
            },
        },
    },
    {
        "name": "get_session",
        "api_mode": "",
        "parameters": {
            "type": "object",
            "required": ["user_id", "session_id"],
            "properties": {"user_id": {"type": "string"}, "session_id": {"type": "string"}},
        },
    },
    {
        "name": "list_sessions",
        "api_mode": "",
        "parameters": {
            "type": "object",
            "required": ["user_id"],
            "properties": {"user_id": {"type": "string"}},
        },
    },
    {
        "name": "delete_session",
        "api_mode": "",
        "parameters": {
            "type": "object",
            "required": ["user_id", "session_id"],
            "properties": {"user_id": {"type": "string"}, "session_id": {"type": "string"}},
        },
    },
    {
        "name": "async_create_session",
        "api_mode": "async",
        "parameters": {
            "type": "object",
            "required": ["user_id"],
            "properties": {
                "user_id": {"type": "string"},
                "session_id": {"type": "string", "nullable": True},
                "state": {"type": "object", "nullable": True},
            },
        },
    },
    {
        "name": "async_get_session",
        "api_mode": "async",
        "parameters": {
            "type": "object",
            "required": ["user_id", "session_id"],
            "properties": {"user_id": {"type": "string"}, "session_id": {"type": "string"}},
        },
    },
    {
        "name": "async_list_sessions",
        "api_mode": "async",
        "parameters": {
            "type": "object",
            "required": ["user_id"],
            "properties": {"user_id": {"type": "string"}},
        },
    },
    {
        "name": "async_delete_session",
        "api_mode": "async",
        "parameters": {
            "type": "object",
            "required": ["user_id", "session_id"],
            "properties": {"user_id": {"type": "string"}, "session_id": {"type": "string"}},
        },
    },
    {
        "name": "async_add_session_to_memory",
        "api_mode": "async",
        "parameters": {
            "type": "object",
            "required": ["session"],
            "properties": {"session": {"type": "object", "additionalProperties": True}},
        },
    },
    {
        "name": "async_search_memory",
        "api_mode": "async",
        "parameters": {
            "type": "object",
            "required": ["user_id", "query"],
            "properties": {"user_id": {"type": "string"}, "query": {"type": "string"}},
        },
    },
]

# ---------------------------------------------------------------------------
# Reserved environment variables
# ---------------------------------------------------------------------------
# Agent Engine sets these automatically in the deployed container.
# Passing them in env_vars causes conflicts, so we filter them out.

RESERVED_ENV_VARS = {
    "GOOGLE_CLOUD_PROJECT",
    "GOOGLE_CLOUD_QUOTA_PROJECT",
    "GOOGLE_CLOUD_LOCATION",
    "GOOGLE_APPLICATION_CREDENTIALS",
    "PORT",
    "K_SERVICE",
    "K_REVISION",
    "K_CONFIGURATION",
}


# ===========================================================================
# Helper functions
# ===========================================================================

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Deploy an ADK agent to Vertex AI Agent Engine.",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--update", action="store_true", help="Update existing deployment")
    group.add_argument("--delete", action="store_true", help="Delete deployment")
    group.add_argument("--info", action="store_true", help="Show deployment info")
    group.add_argument("--test", action="store_true", help="Test deployed agent")
    parser.add_argument(
        "--skip-local-test", action="store_true", help="Skip local smoke test before deploying"
    )
    return parser.parse_args()


# --- Deployment state (JSON file) ---

def _load_deployment() -> dict:
    """Load deployment metadata from the JSON file."""
    if DEPLOYMENT_FILE.exists():
        try:
            return json.loads(DEPLOYMENT_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _save_deployment(metadata: dict) -> None:
    """Save deployment metadata to the JSON file."""
    DEPLOYMENT_FILE.parent.mkdir(parents=True, exist_ok=True)
    DEPLOYMENT_FILE.write_text(json.dumps(metadata, indent=2) + "\n")


# --- Source packages ---

def _get_source_packages() -> list[str]:
    """Collect all agent_* directories, deploy/, and root .py files as source packages.

    Source-file deployment uploads these to Agent Engine.
    The total size must be under 8 MB.
    """
    packages = []
    for item in sorted(PROJECT_ROOT.iterdir()):
        if item.is_dir() and item.name.startswith("agent_") and (item / "__init__.py").exists():
            packages.append(item.name)
    # Include deploy/ so Agent Engine can find the entrypoint module
    packages.append("deploy")
    # Include root .py files that agents import (e.g., config.py)
    for item in sorted(PROJECT_ROOT.glob("*.py")):
        packages.append(item.name)
    return packages


def _write_requirements_file() -> Path:
    """Generate requirements.txt from pyproject.toml dependencies.

    Agent Engine reads this file at build time to install dependencies
    in the deployed container. The file is written to the project root
    so it can be included as a source package.
    """
    with open(PROJECT_ROOT / "pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    deps = data.get("project", {}).get("dependencies", [])

    req_path = PROJECT_ROOT / "requirements.txt"
    req_path.write_text("\n".join(deps) + "\n")
    return req_path


# --- Environment variables ---

def _get_env_vars() -> dict[str, str]:
    """Collect environment variables to pass to the deployed agent.

    Reads from .env, filters out reserved vars that Agent Engine sets
    automatically, and enables telemetry for Cloud Trace.
    """
    env_vars = {}

    # Read declared vars from .env (not all of os.environ)
    env_path = PROJECT_ROOT / ".env"
    if env_path.exists():
        declared = dotenv.dotenv_values(env_path)
        for key, val in declared.items():
            if val and key not in RESERVED_ENV_VARS and not key.startswith("GOOGLE_CLOUD_AGENT_ENGINE"):
                env_vars[key] = val

    # Always enable telemetry (Cloud Trace + prompt/response logging)
    env_vars["GOOGLE_CLOUD_AGENT_ENGINE_ENABLE_TELEMETRY"] = "true"
    env_vars["OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT"] = "true"

    return env_vars


# --- Vertex AI client ---

def _get_client():
    """Create a vertexai.Client for the configured project."""
    import vertexai

    project = os.getenv("GOOGLE_CLOUD_PROJECT", "")
    location = os.getenv("GOOGLE_CLOUD_LOCATION", "us-central1")

    if not project:
        print("Error: GOOGLE_CLOUD_PROJECT not set. Add it to your .env file.")
        sys.exit(1)

    vertexai.init(project=project, location=location)
    return vertexai.Client(project=project, location=location)


def _console_url(resource_name: str) -> str:
    """Build a Cloud Console URL from a resource name."""
    parts = resource_name.split("/")
    if len(parts) >= 6:
        project, location, engine_id = parts[1], parts[3], parts[5]
        return (
            f"https://console.cloud.google.com/vertex-ai/agents/"
            f"locations/{location}/reasoning-engines/{engine_id}"
            f"?project={project}"
        )
    return ""


# --- Local smoke test ---

def _local_test() -> bool:
    """Run a quick local test to verify the agent works before deploying."""
    import importlib

    from vertexai.agent_engines import AdkApp

    print("\nRunning local smoke test...")
    mod = importlib.import_module(ENTRYPOINT_MODULE)
    agent = getattr(mod, ENTRYPOINT_OBJECT)
    app = AdkApp(agent=agent, enable_tracing=True)

    async def _test():
        responses = []
        async for event in app.async_stream_query(
            user_id="deploy_test_user", message=TEST_MESSAGE,
        ):
            if event.get("content"):
                responses.append(event["content"])

        # Clean up test session
        sessions = await app.async_list_sessions(user_id="deploy_test_user")
        for s in sessions.sessions:
            await app.async_delete_session(user_id="deploy_test_user", session_id=s.id)

        return len(responses) > 0

    try:
        success = asyncio.run(_test())
        print("Local test passed." if success else "Local test returned no responses.")
        return success
    except Exception as e:
        print(f"Local test failed: {e}")
        return False


# ===========================================================================
# Commands
# ===========================================================================

def cmd_info() -> None:
    """Show current deployment info."""
    meta = _load_deployment()
    if not meta or not meta.get("resource_name"):
        print("No active deployment found.")
        return

    print("\nDeployment info:")
    for key, val in meta.items():
        print(f"  {key}: {val}")

    url = _console_url(meta["resource_name"])
    if url:
        print(f"\n  Console URL: {url}")


def cmd_delete() -> None:
    """Delete the deployed agent."""
    meta = _load_deployment()
    resource_name = meta.get("resource_name", "")
    if not resource_name:
        print("No active deployment to delete.")
        return

    client = _get_client()
    print(f"\nDeleting deployment: {resource_name}")
    client.agent_engines.delete(name=resource_name, force=True)
    _save_deployment({})
    print("Deployment deleted.")


def cmd_test() -> None:
    """Send a test query to the deployed agent."""
    meta = _load_deployment()
    resource_name = meta.get("resource_name", "")
    if not resource_name:
        print("No active deployment to test.")
        return

    client = _get_client()
    print(f"\nTesting deployed agent: {resource_name}")
    remote_agent = client.agent_engines.get(name=resource_name)

    async def _test():
        session = await remote_agent.async_create_session(user_id="deploy_test_user")
        session_id = session["id"]
        print(f"  Session: {session_id}")
        print(f"  Message: {TEST_MESSAGE}")
        print("  Response:")

        async for event in remote_agent.async_stream_query(
            user_id="deploy_test_user", session_id=session_id, message=TEST_MESSAGE,
        ):
            content = event.get("content")
            if content:
                print(f"    {content}")

        await remote_agent.async_delete_session(
            user_id="deploy_test_user", session_id=session_id,
        )

    asyncio.run(_test())
    print("\nTest complete.")


def cmd_update() -> None:
    """Update an existing deployment with latest code and config."""
    meta = _load_deployment()
    resource_name = meta.get("resource_name", "")
    if not resource_name:
        print("No active deployment to update. Run without --update to create one.")
        return

    client = _get_client()
    source_packages = _get_source_packages()
    env_vars = _get_env_vars()
    req_path = _write_requirements_file()
    all_packages = source_packages + [req_path.name]

    print(f"\nUpdating deployment: {resource_name}")
    print(f"  Source packages: {source_packages}")

    # Change to project root so source package paths resolve correctly
    original_cwd = os.getcwd()
    os.chdir(str(PROJECT_ROOT))
    try:
        client.agent_engines.update(
            name=resource_name,
            config={
                "source_packages": all_packages,
                "entrypoint_module": ENTRYPOINT_MODULE,
                "entrypoint_object": ENTRYPOINT_OBJECT,
                "requirements_file": req_path.name,
                "class_methods": ADK_CLASS_METHODS,
                "display_name": DISPLAY_NAME,
                "description": DESCRIPTION,
                "env_vars": env_vars,
                "agent_framework": "google-adk",
            },
        )
    finally:
        os.chdir(original_cwd)
        req_path.unlink(missing_ok=True)

    meta["last_updated_at"] = datetime.now().isoformat()
    _save_deployment(meta)
    print("Deployment updated.")


def cmd_deploy(skip_local_test: bool) -> None:
    """Create a new deployment on Agent Engine."""
    meta = _load_deployment()
    resource_name = meta.get("resource_name", "")

    client = _get_client()

    # Check for existing deployment
    if resource_name:
        try:
            client.agent_engines.get(name=resource_name)
            print(f"\nExisting deployment found: {resource_name}")
            print("Use --update to update or --delete to remove it.")
            return
        except Exception:
            print(f"Previous deployment {resource_name} not found, creating new one.")

    # Local smoke test
    if not skip_local_test:
        if not _local_test():
            print("\nLocal test failed. Use --skip-local-test to deploy anyway.")
            sys.exit(1)

    source_packages = _get_source_packages()
    env_vars = _get_env_vars()
    req_path = _write_requirements_file()
    all_packages = source_packages + [req_path.name]

    print(f"\nDeploying to Agent Engine...")
    print(f"  Display name:    {DISPLAY_NAME}")
    print(f"  Entrypoint:      {ENTRYPOINT_MODULE}:{ENTRYPOINT_OBJECT}")
    print(f"  Source packages: {all_packages}")
    print(f"  Env vars:        {list(env_vars.keys())}")

    # Change to project root so source package paths resolve correctly
    original_cwd = os.getcwd()
    os.chdir(str(PROJECT_ROOT))
    try:
        remote_agent = client.agent_engines.create(
            config={
                "source_packages": all_packages,
                "entrypoint_module": ENTRYPOINT_MODULE,
                "entrypoint_object": ENTRYPOINT_OBJECT,
                "requirements_file": req_path.name,
                "class_methods": ADK_CLASS_METHODS,
                "display_name": DISPLAY_NAME,
                "description": DESCRIPTION,
                "env_vars": env_vars,
                "agent_framework": "google-adk",
            },
        )
    finally:
        os.chdir(original_cwd)
        req_path.unlink(missing_ok=True)

    # Save deployment metadata
    new_meta = {
        "resource_name": remote_agent.api_resource.name,
        "deployed_at": datetime.now().isoformat(),
        "display_name": DISPLAY_NAME,
        "description": DESCRIPTION,
    }
    _save_deployment(new_meta)

    print(f"\nDeployment created: {new_meta['resource_name']}")
    url = _console_url(new_meta["resource_name"])
    if url:
        print(f"Console URL: {url}")
    print(f"\nMetadata saved to {DEPLOYMENT_FILE.relative_to(PROJECT_ROOT)}")


# ===========================================================================
# Main
# ===========================================================================

def main() -> None:
    args = _parse_args()

    if args.info:
        cmd_info()
    elif args.delete:
        cmd_delete()
    elif args.test:
        cmd_test()
    elif args.update:
        cmd_update()
    else:
        cmd_deploy(skip_local_test=args.skip_local_test)


if __name__ == "__main__":
    main()
