[project]
name = "travel-planner-a2a-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
"a2a-sdk",
"google-genai",
"google-cloud-aiplatform",
"dotenv",
"uvicorn",
"mcp",
"google-adk",
"toolbox-core"
]
