-- Scheduled Queries — BigQuery ML Pipeline
-- =============================================================
-- Takes pipelines/sql_scripting/'s exact drift-check -> conditional-retrain
-- -> SELECT ERROR() script, unchanged, and schedules it via the BigQuery
-- Data Transfer API (the same mechanism behind BigQuery Studio's "Scheduled
-- queries" UI). No new BQML logic here -- this notebook's real content is
-- the scheduling/triggering/alerting layer around an unchanged script.
--
-- Modernizes: MLOps/Model Monitoring/bqml-model-monitoring-tutorial.ipynb's
-- "From Job To Scheduled Query" section (same TransferConfig/
-- ScheduleOptions/EmailPreferences/StartManualTransferRuns pattern). That
-- tutorial's script uses the @run_date pseudo-parameter for rolling
-- date windows against a live-growing serving table; this pipeline's
-- underlying script (pipelines/sql_scripting/) instead uses fixed literal
-- dates against a frozen historical GA4 export, so @run_date isn't needed
-- here -- an honest, disclosed difference, not an oversight.
--
-- Workflow operationalized: ../../workflows/ga4_churn_prediction/
-- Data: bigquery-public-data.ga4_obfuscated_sample_ecommerce
--
-- Full reference: ../../RESOURCES.md
-- Official docs:
--   Scheduling queries: https://cloud.google.com/bigquery/docs/scheduling-queries
--   Python client for BigQuery Data Transfer: https://cloud.google.com/python/docs/reference/bigquerydatatransfer/latest


-- =============================================================================
-- Setup: identical to pipelines/sql_scripting/ -- self-contained feature
-- table + initial "production" model (own copies; not shared across
-- notebooks, since each pipeline notebook's own cleanup drops its objects).
-- =============================================================================
-- (Same feature-table and initial-model SQL as pipelines/sql_scripting/.sql
-- -- see that file for the full query text; omitted here to avoid
-- duplication.)


-- =============================================================================
-- The scheduled script: unchanged from pipelines/sql_scripting/
-- =============================================================================
-- See pipelines/sql_scripting/sql_scripting.sql's "The pipeline script"
-- section for the full DECLARE/SET/IF/BEGIN...END/SELECT ERROR() text --
-- this notebook passes that exact string as the `query` param of a
-- TransferConfig, unmodified.


-- =============================================================================
-- Python: create the scheduled query (see notebook for full code)
-- =============================================================================
-- from google.cloud import bigquery_datatransfer
-- from datetime import datetime, timezone, timedelta
--
-- transfer_client = bigquery_datatransfer.DataTransferServiceClient()
-- parent = transfer_client.common_location_path(PROJECT_ID, 'us')
--
-- request = bigquery_datatransfer.CreateTransferConfigRequest(
--     parent=parent,
--     transfer_config=bigquery_datatransfer.TransferConfig(
--         display_name='GA4 Churn Pipeline Monitoring (bq-ml demo)',
--         data_source_id='scheduled_query',
--         params={'query': pipeline_script},
--         schedule='every 24 hours',
--         schedule_options=bigquery_datatransfer.ScheduleOptions(
--             start_time=datetime.now(timezone.utc) + timedelta(days=2)
--             # pushes the FIRST automatic run 2 days out so it can't race
--             # the manual demo run triggered immediately below -- both
--             # target the same CREATE OR REPLACE MODEL and BigQuery
--             # genuinely rejects concurrent writers to one model (verified
--             # live: "Model can not be updated by multiple create model
--             # query jobs at the same time" when they collided). A real
--             # production schedule wouldn't need this -- it's purely to
--             # keep this notebook's demo run isolated and repeatable.
--         ),
--         email_preferences=bigquery_datatransfer.EmailPreferences(
--             enable_failure_email=True
--         ),
--     ),
--     # A direct API-created transfer config needs an explicit runtime
--     # identity -- verified live: omitting this raises "Failed to find a
--     # valid credential. The field 'version_info' or 'service_account_name'
--     # must be specified." (Console-created schedules get this via an
--     # interactive OAuth consent step instead.)
--     service_account_name='COMPUTE_SA@developer.gserviceaccount.com',
-- )
-- scheduled_query = transfer_client.create_transfer_config(request=request)


-- =============================================================================
-- Trigger a manual run now (a real backfill call, not waiting 24 hours)
-- =============================================================================
-- backfill_job = transfer_client.start_manual_transfer_runs(
--     request=bigquery_datatransfer.StartManualTransferRunsRequest(
--         parent=scheduled_query.name,
--         requested_run_time=datetime.now(timezone.utc),
--     )
-- )
-- # poll transfer_client.get_transfer_run(name=...).state.name until terminal
-- Verified live: FAILED is the CORRECT terminal state here -- the same
-- SELECT ERROR() idiom sql_scripting uses to pass its report through as the
-- job's (and therefore the transfer run's) error message, which
-- email_preferences.enable_failure_email would forward as a real failure
-- alert email. A state of SUCCEEDED would mean the ELSE branch fired (no
-- drift, no report) -- see pipelines/sql_scripting/ for that quiet path.
--
-- Verified live, clean run (fresh initial model, no schedule/backfill
-- race): roc_auc before retrain ~0.74, after retrain ~0.77 -- same real,
-- positive retrain outcome as pipelines/sql_scripting/, delivered this time
-- through a scheduled/triggered run rather than a direct client.query() call.
-- (BOOSTED_TREE_CLASSIFIER has a small amount of run-to-run training
-- variation -- exact figures drift slightly across runs.)


-- =============================================================================
-- Cleanup
-- =============================================================================
-- transfer_client.delete_transfer_config(name=scheduled_query.name)
-- DROP MODEL IF EXISTS `PROJECT_ID.DATASET.ga4_churn_pipeline_model`;
-- DROP TABLE IF EXISTS `PROJECT_ID.DATASET.ga4_churn_pipeline_features`;
