"""Write the two LookML models to `looker/` for a human to install.

    uv run python scripts/generate_lookml.py

Overwrites `looker/` in place — it is generated output, not a place to hand-edit.
Change `src/corpus.py` or `src/lookml.py` and re-run.

Only the LookML *files* need a human: Looker has no file-write API. Everything
else (connections, models, roles, users) is done by `scripts/looker_provision.py`.
"""

import shutil
import sys
from pathlib import Path

import _bootstrap  # noqa: F401 - import for the sys.path side effect

import config
import lookml

OUTPUT = Path(__file__).resolve().parent.parent / "looker"

README = """# LookML for the sandbox (generated)

**Generated by `scripts/generate_lookml.py` — do not hand-edit.** Change
`src/corpus.py` or `src/lookml.py` and re-run, so the semantic layer cannot drift
from the BigQuery corpus or the golden-truth oracle.

Two models, one per governance tier. They are the Looker half of the tier
experiment (`DESIGN.md` §6.3):

- **`{t0}`** — raw passthrough. Dimensions only, **no measures**, no
  descriptions. An agent has to assemble revenue itself, and can pick the wrong
  column exactly as it would against a bare schema.
- **`{t1}`** — adds `total_revenue` (net, refunds excluded) and
  `active_user_status` (the governed Active definition), each carrying its rule
  as a field description.

## One connection per tier

`manifest.lkml` declares `LOOKER_CONNECTION_T0` and `LOOKER_CONNECTION_T1`, and
each model file names its own. That is deliberate and load-bearing: a Looker
connection authenticates as **the connection**, not as the calling user, so a
single shared connection would make Path 2 the only arm whose tier boundary was
not enforced by IAM. Each connection is ADC + *Impersonated Service Account* set
to that tier's sandbox identity, so a cross-tier read returns a 403 exactly as it
does on the other paths — and no key file is involved.

## Installing

Most of this is scripted. From the repo root, with **admin** API3 credentials
exported:

```bash
uv run python scripts/looker_provision.py           # dry run
uv run python scripts/looker_provision.py --apply   # create
```

That creates both connections, the project shell, both model configurations, the
model sets, roles, non-admin sweep users with fresh API3 credentials, and the
OAuth client app — and refuses to modify anything already on the instance.

Two steps it cannot do:

1. **The LookML files.** Looker has no file-write API (`project_file` is
   read-only), so copy this directory into the `data_mcp_sandbox` project via the
   Looker IDE, or point the project at a Git remote containing it. Then **Deploy
   to Production** — models are invisible to the API until they are in production.
2. **Grant Looker impersonation rights** on the tier service accounts. That is a
   GCP IAM change, handled by `scripts/bootstrap_identities.sh`.

Verify with `uv run python scripts/setup.py` (or `make setup`), which fails loudly
if a model is missing, an Explore does not resolve, tier 0 has picked up a
measure, or the sweep credentials can see a model this sandbox does not own.
"""


def main() -> int:
    if OUTPUT.exists():
        shutil.rmtree(OUTPUT)

    files = lookml.render_all()
    for relative, content in files.items():
        path = OUTPUT / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"    {path.relative_to(OUTPUT.parent)}")

    readme = README.format(t0=config.looker_model(0), t1=config.looker_model(1))
    (OUTPUT / "README.md").write_text(readme)
    print(f"    looker/README.md\n\n{len(files) + 1} files written. Install per looker/README.md.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
