from .function_tool_bq_hurricanes_per_year import function_tool_bq_hurricanes_per_year
from .function_tool_bq_hurricanes_per_year_filtered import function_tool_bq_hurricanes_per_year_filtered

PYTHON_FUNCTION_TOOLS = [
    function_tool_bq_hurricanes_per_year,
    function_tool_bq_hurricanes_per_year_filtered,
]