[project]
name = "concept-bq"
version = "0.1.0"
description = "An ADK example that shows multiple ways of having Agent Query BigQuery"
authors = [
    {name = "Mike Henderson",email = "statmike@gmail.com"}
]
readme = "README.md"
requires-python = "^3.13"
dependencies = [
    "google-cloud-bigquery (>=3.36.0,<4.0.0)",
    "google-adk (>=1.12.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
